import Link from 'next/link';
import { PoolCard } from '../components/pool-card';
import { SiteFooter, SiteHeader } from '../components/site-header';
import { apiGet } from '../lib/api';
import { modalityNames, money, PublicContest, PublicPool, shortDate } from '../lib/domain';

export default async function HomePage() {
  const [poolResult, contestResult] = await Promise.all([apiGet<PublicPool[]>('/boloes'), apiGet<PublicContest[]>('/concursos')]);
  const pools = poolResult.data ?? [];
  const contests = contestResult.data ?? [];
  const featured = contests.filter(item => new Date(item.cutoffAt) > new Date()).sort((a, b) => Number(b.valorEstimadoPremio ?? 0) - Number(a.valorEstimadoPremio ?? 0))[0];
  return <><SiteHeader /><main>
    <section className="hero shell"><div className="hero-copy"><span className="live-label"><i /> Concursos oficiais atualizados</span><h1>Seu bolão, do jeito <em>livre</em> de participar.</h1><p>Escolha uma participação, acompanhe cada etapa e encontre suas cotas e comprovantes em um só lugar.</p><div className="hero-actions"><Link className="button button-primary button-large" href="#boloes">Ver bolões disponíveis</Link><Link className="text-link" href="#como-funciona">Como funciona <span>→</span></Link></div><div className="trust-row"><span>✓ Cotas rastreáveis</span><span>✓ Pagamento protegido</span><span>✓ Resultado oficial</span></div></div>
      <div className="featured-draw"><div className="featured-glow"/><div className="featured-logo"><img src="/brand/bl-logo-horizontal-color.png" alt="BL — Bolão Livre" /></div><div className="featured-head"><span>Maior prêmio disponível</span><span className="live-pill">Atualizado</span></div>{featured ? <><p className="lottery-name">{modalityNames[featured.modalidade] ?? featured.modalidade}</p><strong className="prize-value">{money(featured.valorEstimadoPremio)}</strong><div className="draw-data"><span>Concurso <strong>{featured.numeroConcurso}</strong></span><span>Sorteio <strong>{shortDate(featured.dataSorteio)}</strong></span></div><Link href="#boloes" className="featured-link">Encontrar um bolão <span>→</span></Link></> : <div className="empty-compact"><strong>Sincronização em preparação</strong><p>Os próximos concursos aparecerão assim que o serviço oficial for sincronizado.</p></div>}</div>
    </section>
    <section className="numbers-strip"><div className="shell"><span><strong>{contests.length}</strong> concursos no catálogo</span><span><strong>{pools.length}</strong> bolões disponíveis</span><span><strong>100%</strong> histórico rastreável</span><span><strong>18+</strong> acesso exclusivo para adultos</span></div></section>
    <section className="section shell" id="boloes"><div className="section-title"><div><span className="overline">Escolha sua participação</span><h2>Bolões em destaque</h2><p>Valores, disponibilidade e prazo apresentados antes da confirmação.</p></div></div>{poolResult.error ? <div className="notice notice-error"><strong>Catálogo temporariamente indisponível</strong><span>{poolResult.error}</span></div> : pools.length ? <div className="pool-grid">{pools.map(pool => <PoolCard pool={pool} key={pool.id}/>)}</div> : <div className="empty-state"><span>BL</span><h3>O primeiro bolão será exibido aqui</h3><p>O banco está conectado, mas ainda não existem bolões abertos. Um administrador deve sincronizar os concursos e cadastrar a primeira oferta.</p><Link className="button button-secondary" href="/admin">Ir para a administração</Link></div>}</section>
    <section className="section soft-section" id="concursos"><div className="shell"><div className="section-title"><div><span className="overline">Calendário</span><h2>Próximos concursos</h2></div></div><div className="contest-list">{contests.slice(0, 6).map(contest => <article key={contest.id}><span className={`contest-icon ${contest.modalidade}`}>BL</span><div><strong>{modalityNames[contest.modalidade] ?? contest.modalidade}</strong><small>Concurso {contest.numeroConcurso}</small></div><div><small>Prêmio estimado</small><strong>{money(contest.valorEstimadoPremio)}</strong></div><div><small>Sorteio</small><strong>{shortDate(contest.dataSorteio)}</strong></div></article>)}{!contests.length && <p className="muted">Nenhum concurso sincronizado.</p>}</div></div></section>
    <section className="section shell steps" id="como-funciona"><div className="section-title centered"><div><span className="overline">Simples e transparente</span><h2>Da escolha ao resultado</h2></div></div><div className="steps-grid"><article><span>1</span><h3>Escolha o bolão</h3><p>Confira concurso, valor, taxa e cotas disponíveis.</p></article><article><span>2</span><h3>Reserve suas cotas</h3><p>Entre na sua conta e confirme os dados da participação.</p></article><article><span>3</span><h3>Pague com segurança</h3><p>Use o Pix e acompanhe a confirmação dentro do BL.</p></article><article><span>4</span><h3>Acompanhe tudo</h3><p>Consulte comprovante, resultado e eventual premiação.</p></article></div></section>
  </main><SiteFooter /></>;
}
