import Image from 'next/image';
import Link from 'next/link';
import { LotteryCatalog } from '../components/lottery-catalog';
import { ModalityShowcase } from '../components/modality-showcase';
import { SiteFooter, SiteHeader } from '../components/site-header';
import { apiGet } from '../lib/api';
import { lotteryVisual } from '../lib/lottery-config';
import { modalityNames, money, PublicContest, PublicPool, shortDate } from '../lib/domain';

export default async function HomePage() {
  const [poolResult, contestResult] = await Promise.all([apiGet<PublicPool[]>('/boloes'), apiGet<PublicContest[]>('/concursos')]);
  const pools = poolResult.data ?? [];
  const contests = contestResult.data ?? [];
  const featured = contests.filter((item) => new Date(item.cutoffAt).getTime() > Date.now()).sort((a, b) => Number(b.valorEstimadoPremio ?? 0) - Number(a.valorEstimadoPremio ?? 0))[0] ?? contests[0];
  const featuredVisual = lotteryVisual(featured?.modalidade);
  const openPools = pools.filter((pool) => pool.status === 'aberto' && pool.cotasDisponiveis > 0).length;
  const openContests = contests.filter((contest) => new Date(contest.cutoffAt).getTime() > Date.now()).length;

  return <><SiteHeader /><main>
    <section className="hero shell"><div className="hero-copy"><span className="live-label"><i /> Concursos oficiais atualizados</span><h1>Mais chances começam com uma <em>boa escolha.</em></h1><p>Encontre o concurso certo, escolha suas cotas e acompanhe cada etapa com a clareza do BL — Bolão Livre.</p><div className="hero-actions"><Link className="button button-primary button-large" href="#boloes">Ver bolões disponíveis <span aria-hidden="true">→</span></Link><Link className="text-link" href="#modalidades">Explorar modalidades <span aria-hidden="true">↓</span></Link></div><div className="trust-row"><span><b>✓</b> Cotas rastreáveis</span><span><b>✓</b> Resultado oficial</span><span><b>✓</b> Jogo responsável</span></div></div>
      <div className="featured-draw"><div className="featured-art"><Image src={featuredVisual.art} alt="" fill priority sizes="(max-width: 960px) 100vw, 560px" /><div className="featured-art-shade" /></div><div className="featured-content"><div className="featured-head"><span>Concurso em destaque</span><span className="live-pill">● Atualizado</span></div>{featured ? <><p className="lottery-name">{modalityNames[featured.modalidade] ?? featured.modalidade}</p><strong className="prize-value">{money(featured.valorEstimadoPremio)}</strong><div className="draw-data"><span>Concurso <strong>{featured.numeroConcurso}</strong></span><span>Sorteio <strong>{shortDate(featured.dataSorteio)}</strong></span></div><Link href="#boloes" className="featured-link">Encontrar um bolão <span aria-hidden="true">→</span></Link></> : <div className="empty-compact"><strong>Sincronização em preparação</strong><p>Os próximos concursos aparecerão assim que o serviço oficial for sincronizado.</p></div>}</div></div>
    </section>
    <section className="numbers-strip"><div className="shell"><span><strong>{openContests}</strong> concursos abertos</span><span><strong>{openPools}</strong> bolões com cotas</span><span><strong>{contests.length}</strong> modalidades monitoradas</span><span><strong>18+</strong> experiência responsável</span></div></section>
    <section className="section shell" id="modalidades"><div className="section-title"><div><span className="overline">Escolha pelo seu momento</span><h2>As modalidades mais procuradas</h2><p>Visuais próprios para cada jogo, com informações sempre atualizadas em texto.</p></div><Link className="section-link" href="#concursos">Ver calendário <span aria-hidden="true">→</span></Link></div><ModalityShowcase contests={contests} /></section>
    <section className="section soft-section" id="boloes"><div className="shell"><div className="section-title"><div><span className="overline">Catálogo BL</span><h2>Bolões disponíveis para você</h2><p>Compare cotas, prêmio estimado e prazo antes de participar.</p></div><span className="section-note"><b>{openPools}</b> oportunidades abertas agora</span></div>{poolResult.error ? <div className="notice notice-error"><strong>Catálogo temporariamente indisponível</strong><span>{poolResult.error}</span></div> : <LotteryCatalog pools={pools} />}</div></section>
    <section className="section shell" id="concursos"><div className="section-title"><div><span className="overline">Calendário oficial</span><h2>Próximos concursos</h2><p>Confira prêmio, concurso e data de sorteio em um só lugar.</p></div><span className="section-note"><i className="status-dot-indicator" /> Atualização automática</span></div><div className="contest-list">{contests.slice(0, 8).map((contest) => <article key={contest.id}><span className={`contest-icon ${contest.modalidade}`}>{lotteryVisual(contest.modalidade).icon}</span><div><strong>{modalityNames[contest.modalidade] ?? contest.modalidade}</strong><small>Concurso {contest.numeroConcurso}</small></div><div><small>Prêmio estimado</small><strong>{money(contest.valorEstimadoPremio)}</strong></div><div><small>Sorteio</small><strong>{shortDate(contest.dataSorteio)}</strong></div><span className={`contest-status ${new Date(contest.cutoffAt).getTime() > Date.now() ? 'is-open' : 'is-closed'}`}>{new Date(contest.cutoffAt).getTime() > Date.now() ? 'Aberto' : 'Encerrado'}</span></article>)}{!contests.length && <p className="muted empty-list">Nenhum concurso sincronizado.</p>}</div></section>
    <section className="section dark-section" id="como-funciona"><div className="shell"><div className="section-title dark-title"><div><span className="overline">Uma jornada mais clara</span><h2>Do concurso ao comprovante</h2><p>Informação objetiva para você decidir no seu ritmo.</p></div></div><div className="steps-grid"><article><span>01</span><h3>Escolha a modalidade</h3><p>Compare jogos, prêmios estimados e datas em uma navegação simples.</p></article><article><span>02</span><h3>Encontre sua cota</h3><p>Veja disponibilidade, valor, taxa e composição da participação.</p></article><article><span>03</span><h3>Reserve com segurança</h3><p>Confirme seus dados e acompanhe a reserva dentro da sua conta.</p></article><article><span>04</span><h3>Acompanhe o resultado</h3><p>Tenha histórico, comprovantes e status da sua participação.</p></article></div><div className="responsible-note"><strong>Jogue com responsabilidade.</strong><span>O BL é uma plataforma independente, não oficial da CAIXA, e o acesso é destinado a maiores de 18 anos.</span><Link href="/termos">Conheça as regras <span aria-hidden="true">→</span></Link></div></div></section>
  </main><SiteFooter /></>;
}
