'use client';
import { FormEvent, useEffect, useState } from 'react';
import { modalityNames, money, PublicContest, PublicPool } from '../lib/domain';

type Group = { id: string; nome: string }; type User = { papel: string; nome: string }; type Reconciliation = { valorArrecadado: string; taxaAdministracao: string; custoBilhetes: string; comissoes: string };
async function authFetch(path:string, options?:RequestInit){let response=await fetch(path,{...options,credentials:'include'});if(response.status===401){const refresh=await fetch('/api/v1/auth/refresh',{method:'POST',credentials:'include'});if(refresh.ok)response=await fetch(path,{...options,credentials:'include'});}return response;}

export function AdminDashboard(){
  const [user,setUser]=useState<User|null>(null);const [contests,setContests]=useState<PublicContest[]>([]);const [pools,setPools]=useState<PublicPool[]>([]);const [group,setGroup]=useState<Group|null>(null);const [finance,setFinance]=useState<Reconciliation|null>(null);const [message,setMessage]=useState('');const [loading,setLoading]=useState(true);
  async function load(){try{const [me,c,g,p,f]=await Promise.all([authFetch('/api/v1/auth/me'),fetch('/api/v1/concursos'),fetch('/api/v1/grupos/bl-oficial'),fetch('/api/v1/boloes'),authFetch('/api/v1/admin/financeiro/conciliacao')]);if(me.status===401){window.location.href='/login';return;}const current=await me.json() as User;if(current.papel!=='admin'){setMessage('Este acesso exige perfil de administrador.');return;}setUser(current);if(c.ok)setContests(await c.json());if(g.ok)setGroup(await g.json());if(p.ok)setPools(await p.json());if(f.ok)setFinance(await f.json());}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  async function sync(){setMessage('Sincronizando concursos…');const response=await authFetch('/api/v1/admin/concursos/sincronizar',{method:'POST'});const data=await response.json().catch(()=>({})) as {sincronizados?:number;message?:string};setMessage(response.ok?`${data.sincronizados??0} concursos sincronizados.`:data.message||'Falha na sincronização.');if(response.ok)await load();}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!group)return;const form=new FormData(event.currentTarget);const body={concursoId:String(form.get('concursoId')),grupoId:group.id,numerosApostados:String(form.get('numeros')).split(',').map(v=>Number(v.trim())).filter(Number.isFinite),totalCotas:Number(form.get('totalCotas')),valorCota:Number(form.get('valorCota')),taxaAdministracaoPct:Number(form.get('taxa')),modeloOperacional:'mandato'};const response=await authFetch('/api/v1/admin/boloes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await response.json().catch(()=>({})) as {message?:string|string[]};setMessage(response.ok?'Bolão criado com sucesso.':Array.isArray(data.message)?data.message.join(' '):data.message||'Falha ao criar bolão.');if(response.ok){event.currentTarget.reset();await load();}}
  if(loading)return <div className="empty-state"><span>BL</span><h3>Carregando administração…</h3></div>;
  if(!user)return <div className="notice notice-error"><strong>Acesso não autorizado</strong><span>{message}</span></div>;
  return <><div className="page-heading"><div><span className="overline">Centro de operação</span><h1>Administração BL</h1><p className="muted">Concursos, bolões e conciliação da versão Web.</p></div><button className="button button-primary" onClick={sync}>Sincronizar concursos</button></div>{message&&<div className="form-message form-success">{message}</div>}<div className="dashboard-grid"><article className="dashboard-card"><span className="overline">Concursos</span><strong className="stat-value">{contests.length}</strong></article><article className="dashboard-card"><span className="overline">Bolões</span><strong className="stat-value">{pools.length}</strong></article><article className="dashboard-card"><span className="overline">Arrecadação confirmada</span><strong className="stat-value stat-money">{money(finance?.valorArrecadado)}</strong></article><article className="dashboard-card wide"><h2>Criar bolão</h2><form className="admin-form" onSubmit={create}><div className="field"><label>Concurso</label><select name="concursoId" required><option value="">Selecione</option>{contests.map(item=><option key={item.id} value={item.id}>{modalityNames[item.modalidade]??item.modalidade} · {item.numeroConcurso}</option>)}</select></div><div className="field"><label>Números apostados (separados por vírgula)</label><input name="numeros" placeholder="05, 12, 18, 27, 44, 59" required/></div><div className="field"><label>Total de cotas</label><input name="totalCotas" type="number" min="2" max="100" required/></div><div className="field"><label>Valor da cota</label><input name="valorCota" type="number" min="1" step="0.01" required/></div><div className="field"><label>Taxa administrativa (%)</label><input name="taxa" type="number" min="0.01" max="35" step="0.01" required/></div><button className="button button-primary">Criar bolão</button></form></article>{finance&&<article className="dashboard-card wide"><h2>Conciliação</h2><div className="detail-facts"><div><small>Arrecadado</small><strong>{money(finance.valorArrecadado)}</strong></div><div><small>Taxa administrativa</small><strong>{money(finance.taxaAdministracao)}</strong></div><div><small>Custo dos bilhetes</small><strong>{money(finance.custoBilhetes)}</strong></div><div><small>Comissões</small><strong>{money(finance.comissoes)}</strong></div></div></article>}</div></>;
}
