'use client';

import { useState, type FormEvent, type ReactNode } from 'react';

type AffiliateOption = { id: string; codigoAfiliado?: string; parentAfiliadoId?: string | null; statusAprovacao?: string; usuario?: { nome?: string; email?: string } };
type AffiliateRow = AffiliateOption & { statusAprovacao?: string; indicadores?: { indicados?: number; usuariosIndicados?: number; grupos?: number; cotas?: number }; comissaoPadraoPct?: string };
type NoticeHandler = (message: string) => void;

async function adminRequest(path: string, options?: RequestInit) {
  const response = await fetch(path, { ...options, credentials: 'include' });
  if (response.status === 401) { window.location.href = `/login?next=${encodeURIComponent(window.location.pathname + window.location.search)}`; throw new Error('Sessão expirada.'); }
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(Array.isArray(payload.message) ? payload.message.join(' ') : payload.message || 'Não foi possível concluir.');
  return payload;
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="admin-field"><span>{label}</span>{children}</label>; }

export function ManagedUserForm({ mode, affiliates = [], onDone, onNotice }: { mode: 'user' | 'affiliate'; affiliates?: AffiliateOption[]; onDone?: () => Promise<void> | void; onNotice?: NoticeHandler }) {
  const [form, setForm] = useState({ nome: '', cpf: '', email: '', telefone: '', dataNascimento: '', senha: '', parentAfiliadoId: '', comissaoPadraoPct: '10' });
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const path = mode === 'affiliate' ? '/api/v1/admin/afiliados' : '/api/v1/admin/usuarios'; const result = await adminRequest(path, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...form, parentAfiliadoId: form.parentAfiliadoId || undefined, comissaoPadraoPct: mode === 'affiliate' ? Number(form.comissaoPadraoPct) : undefined }) }); setForm({ nome: '', cpf: '', email: '', telefone: '', dataNascimento: '', senha: '', parentAfiliadoId: '', comissaoPadraoPct: '10' }); setOpen(false); onNotice?.(`${mode === 'affiliate' ? 'Afiliado' : 'Usuário'} criado com sucesso.`); await onDone?.(); return result; } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao criar cadastro.'); } finally { setBusy(false); } }
  return <section className="admin-create-panel"><div className="admin-create-heading"><div><span className="admin-eyebrow">Cadastro interno</span><strong>{mode === 'affiliate' ? 'Adicionar afiliado à rede' : 'Adicionar usuário cotista'}</strong><small>{mode === 'affiliate' ? 'Cria conta, perfil afiliado e código próprio em uma única transação.' : 'Cria uma conta participante com credenciais definidas pelo administrador.'}</small></div><button className="admin-button admin-button-primary" onClick={() => setOpen((value) => !value)}>{open ? 'Fechar formulário' : mode === 'affiliate' ? 'Novo afiliado' : 'Novo usuário'}</button></div>{open && <form className="admin-form-grid admin-form-grid-three admin-create-form" onSubmit={submit}><Field label="Nome completo"><input required minLength={2} value={form.nome} onChange={(event) => update('nome', event.target.value)} /></Field><Field label="CPF (somente números)"><input required minLength={11} maxLength={11} pattern="[0-9]{11}" value={form.cpf} onChange={(event) => update('cpf', event.target.value)} /></Field><Field label="E-mail"><input required type="email" value={form.email} onChange={(event) => update('email', event.target.value)} /></Field><Field label="Telefone"><input value={form.telefone} onChange={(event) => update('telefone', event.target.value)} /></Field><Field label="Nascimento"><input required type="date" value={form.dataNascimento} onChange={(event) => update('dataNascimento', event.target.value)} /></Field><Field label="Senha inicial"><input required minLength={12} type="password" value={form.senha} onChange={(event) => update('senha', event.target.value)} /></Field>{mode === 'affiliate' && <><Field label="Afiliado-pai"><select value={form.parentAfiliadoId} onChange={(event) => update('parentAfiliadoId', event.target.value)}><option value="">Raiz da rede</option>{affiliates.filter((affiliate) => affiliate.statusAprovacao === 'aprovado').map((affiliate) => <option value={affiliate.id} key={affiliate.id}>{affiliate.usuario?.nome ?? affiliate.codigoAfiliado}</option>)}</select></Field><Field label="Comissão padrão (%)"><input required type="number" min="0" max="100" step="0.01" value={form.comissaoPadraoPct} onChange={(event) => update('comissaoPadraoPct', event.target.value)} /></Field></>}{error && <div className="form-message form-error admin-form-feedback">{error}</div>}<div className="admin-form-submit"><button className="admin-button admin-button-primary" disabled={busy}>{busy ? 'Salvando…' : 'Salvar cadastro'}</button></div></form>}</section>;
}

export function InviteManager({ affiliates = [], onDone, onNotice }: { affiliates?: AffiliateOption[]; onDone?: () => Promise<void> | void; onNotice?: NoticeHandler }) {
  const [type, setType] = useState<'usuario' | 'afiliado'>('usuario'); const [origin, setOrigin] = useState(''); const [email, setEmail] = useState(''); const [result, setResult] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); setResult(''); try { const invite = await adminRequest('/api/v1/admin/convites', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ tipo: type, afiliadoOrigemId: origin || undefined, emailDestino: email || undefined }) }); const link = `${window.location.origin}${invite.caminho}`; setResult(link); onNotice?.('Convite criado.'); await onDone?.(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao criar convite.'); } finally { setBusy(false); } }
  return <section className="admin-create-panel"><div className="admin-create-heading"><div><span className="admin-eyebrow">Aquisição</span><strong>Gerar link de convite</strong><small>O cadastro fica atribuído server-side e o link tem validade rastreável.</small></div></div><form className="admin-form-grid" onSubmit={submit}><Field label="Tipo"><select value={type} onChange={(event) => setType(event.target.value as 'usuario' | 'afiliado')}><option value="usuario">Usuário participante</option><option value="afiliado">Afiliado da rede</option></select></Field><Field label="Origem afiliada"><select value={origin} onChange={(event) => setOrigin(event.target.value)}><option value="">Sem origem / raiz</option>{affiliates.filter((affiliate) => affiliate.statusAprovacao === 'aprovado').map((affiliate) => <option value={affiliate.id} key={affiliate.id}>{affiliate.usuario?.nome ?? affiliate.codigoAfiliado}</option>)}</select></Field><Field label="E-mail de destino (opcional)"><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="pessoa@exemplo.com" /></Field><div className="admin-form-submit"><button className="admin-button admin-button-secondary" disabled={busy}>{busy ? 'Gerando…' : 'Gerar convite'}</button></div></form>{result && <div className="admin-generated-link"><div><span>Link gerado</span><strong>{result}</strong></div><button className="admin-button admin-button-primary" onClick={() => navigator.clipboard.writeText(result)}>Copiar link</button></div>}{error && <div className="form-message form-error">{error}</div>}</section>;
}

export function AffiliateNetworkTable({ affiliates, onDone, onNotice }: { affiliates: AffiliateRow[]; onDone?: () => Promise<void> | void; onNotice?: NoticeHandler }) {
  const [busyId, setBusyId] = useState(''); const [error, setError] = useState('');
  async function save(id: string, parentAfiliadoId: string) { setBusyId(id); setError(''); try { await adminRequest(`/api/v1/admin/afiliados/${id}/rede`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ parentAfiliadoId: parentAfiliadoId || null }) }); onNotice?.('Rede atualizada com sucesso.'); await onDone?.(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao atualizar a rede.'); } finally { setBusyId(''); } }
  if (!affiliates.length) return <div className="admin-empty"><span>BL</span><strong>Nenhum afiliado cadastrado</strong><p>Crie o primeiro afiliado ou gere um convite para iniciar a rede.</p></div>;
  return <>{error && <div className="form-message form-error">{error}</div>}<div className="admin-network-tree">{affiliates.map((affiliate) => <div className="admin-network-row" key={affiliate.id}><div className="admin-network-identity"><span className="network-avatar">{(affiliate.usuario?.nome ?? 'AF').slice(0, 2).toUpperCase()}</span><div><strong>{affiliate.usuario?.nome ?? 'Afiliado'}</strong><small>{affiliate.usuario?.email ?? '—'} · {affiliate.codigoAfiliado}</small></div></div><div className="admin-network-metrics"><span>{affiliate.indicadores?.indicados ?? 0} diretos</span><span>{affiliate.indicadores?.usuariosIndicados ?? 0} usuários</span><span>{affiliate.indicadores?.grupos ?? 0} grupos</span><span>{affiliate.indicadores?.cotas ?? 0} cotas</span></div><label className="admin-network-parent"><span>Pai</span><select value={affiliate.parentAfiliadoId ?? ''} disabled={busyId === affiliate.id} onChange={(event) => void save(affiliate.id, event.target.value)}><option value="">Raiz</option>{affiliates.filter((parent) => parent.id !== affiliate.id && parent.statusAprovacao === 'aprovado').map((parent) => <option value={parent.id} key={parent.id}>{parent.usuario?.nome ?? parent.codigoAfiliado}</option>)}</select></label><span className={`status-chip ${affiliate.statusAprovacao === 'aprovado' ? 'status-success' : affiliate.statusAprovacao === 'pendente' ? 'status-warning' : 'status-danger'}`}>{affiliate.statusAprovacao}</span></div>)}</div></>;
}

export function AdminGroupForm({ affiliates = [], onDone, onNotice }: { affiliates?: AffiliateOption[]; onDone?: () => Promise<void> | void; onNotice?: NoticeHandler }) {
  const [form, setForm] = useState({ nome: '', slug: '', descricao: '', afiliadoId: '' }); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await adminRequest('/api/v1/admin/grupos', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...form, afiliadoId: form.afiliadoId || undefined }) }); setForm({ nome: '', slug: '', descricao: '', afiliadoId: '' }); onNotice?.('Grupo criado e vinculado.'); await onDone?.(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao criar grupo.'); } finally { setBusy(false); } }
  return <form className="admin-form-grid admin-form-grid-three admin-create-form" onSubmit={submit}><Field label="Nome"><input required minLength={2} value={form.nome} onChange={(event) => setForm({ ...form, nome: event.target.value })} /></Field><Field label="Slug público"><input required pattern="[a-zA-Z0-9-]+" value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value })} placeholder="grupo-do-afiliado" /></Field><Field label="Proprietário afiliado"><select value={form.afiliadoId} onChange={(event) => setForm({ ...form, afiliadoId: event.target.value })}><option value="">Grupo oficial</option>{affiliates.filter((affiliate) => affiliate.statusAprovacao === 'aprovado').map((affiliate) => <option value={affiliate.id} key={affiliate.id}>{affiliate.usuario?.nome ?? affiliate.codigoAfiliado}</option>)}</select></Field><label className="admin-field admin-field-wide"><span>Descrição</span><textarea value={form.descricao} onChange={(event) => setForm({ ...form, descricao: event.target.value })} /></label>{error && <div className="form-message form-error admin-form-feedback">{error}</div>}<div className="admin-form-submit"><button className="admin-button admin-button-primary" disabled={busy}>{busy ? 'Salvando…' : 'Criar grupo'}</button></div></form>;
}
